fix several typoes
w3c/webcodecs pull request #634
Opened 2023-02-01 06:58 UTC by bdrtc

fix several typoes

2023-02-01 16:01 UTC, padenot requested changes

2023-02-01 16:01 UTC, padenot commented on index.src.html
> -:: The index identifying the plane to copy from.
This is correct.

2023-02-01 16:01 UTC, padenot commented on index.src.html
> -of a multi-channel signal, that happen at the exact same time.
This is correct.

2023-02-01 16:01 UTC, padenot commented on index.src.html
> -and a sample refer to the same thing.
This is correct.

2023-02-02 06:27 UTC, aboba approved these changes

2023-02-02 17:05 UTC, merged