support specify audio encode bitrateMode interface
w3c/webcodecs pull request #657
Opened 2023-03-27 09:48 UTC by bdrtc

fixes #649

2023-03-27 17:18 UTC, dalecurtis commented
Do we want a config level bitrate mode knob like we have for video instead?

2023-03-27 18:09 UTC, Djuffin commented
I agree with @dalecurtis, bitrate mode seems like a very generic knob that will be used for many codecs with the same meaning. 
So I think it belongs in AudioEncoderConfig

2023-03-29 03:28 UTC, bdrtc commented
> AudioEncoderConfig

Thanks feedback, I  considered add this to AudioEncoderConfig before commit, but for audio codec, not all codecs support vbr mode, For example ulaw/alaw, what will happen if user specify a bitrate mode to AudioEncoderConfig that current codec does't supported ?

2023-03-29 03:30 UTC, Djuffin commented
> what will happen if user specify a bitrate mode to AudioEncoderConfig that current codec does't supported ?

[AudioEncoder.isConfigSupported()](https://www.w3.org/TR/webcodecs/#dom-audioencoder-isconfigsupported) will return false.

2023-03-30 03:49 UTC, bdrtc commented
> Do we want a config level bitrate mode knob like we have for video instead?

I will move it to `AudioEncoderConfig` and add a Note, Thanks.

2023-04-18 07:17 UTC, bdrtc commented
Dear editors, any more comments about this ? thanks.

2023-04-18 07:18 UTC, Djuffin commented
LGTM @tguilbert-google please take a look

2023-04-18 07:51 UTC, chrisn requested changes

2023-04-18 07:51 UTC, chrisn commented on index.src.html
> +    Configures encoder to use a {{BitrateMode/constant}} or
Suggest "Configures the encoder"

2023-04-18 07:51 UTC, chrisn commented on index.src.html
> +	NOTE: Not all audio codecs support specific {{BitrateMode}}, Authors are encouraged to check by calling {{AudioEncoder/isConfigSupported()}} with |config|.
Suggest "support specific {{BitrateMode}}s" or "support setting a specific {{BitrateMode}}"

2023-04-19 07:32 UTC, bdrtc commented
> Also LGTM!

Thanks. If there's any questions please let me know when you approve this.

2023-04-19 08:47 UTC, merged