Add to codec registry requirements
w3c/webcodecs pull request #693
Opened 2023-06-23 16:30 UTC by chrisn

This is intended to resolve #426.

- Added a requirement for a public specification that is stable
- Added that the WG may consult external expertise as part of its review (but not go so far as producing a written review with a recommendation, as #426 suggested)
- Fixes the numbering in the source document

@aboba for review

2023-07-04 03:54 UTC, aboba requested changes
Line 48: What does "stable" mean in this context?  Taking the IETF as an example, would an Internet-Draft be considered stable upon WG adoption? Upon approval for publication as an RFC?

2023-07-04 18:52 UTC, chrisn commented
This gives a pretty good set of considerations: https://www.w3.org/2013/09/normative-references#stability

But, adding new registrations is pretty infrequent so I'm wondering whether we really need say anything, and leave to the WG evaluation at the time.

2023-07-05 19:55 UTC, aboba commented
@chrisn I think we should leave it to WG evaluation. 

Note that there are other requirements in the normative reference gujde that codec specifications may not be able to meet.  For example, the specification for EVC  (,"ISO/IEC 23094-1 Essential Video Coding")  is behind a paywall at https://www.iso.org/standard/57797.html  In IETF, the typical requirement is only that versions of the codec specification can be made available to reviewers upon request.

2023-07-05 20:19 UTC, chrisn commented
To allow for paywalled specs we could change the wording from "must include ... a link to a public specification" to "must include ... a reference to the codec's specification" - and we'd similarly want the spec to be made available for review (we have done this from time to time in MEIG).

2023-07-06 16:10 UTC, merged